// Generated by Haxe 4.3.6
#include <hxcpp.h>

namespace hx {
const char *__hxcpp_all_files[] = {
#ifdef HXCPP_DEBUGGER
"/usr/share/haxe/std/cpp/_std/Std.hx",
"/usr/share/haxe/std/cpp/_std/haxe/Log.hx",
"/usr/share/haxe/std/haxe/io/Bytes.hx",
"/usr/share/haxe/std/haxe/iterators/ArrayIterator.hx",
"?",
"Main.hx",
"genesis/Genesis.hx",
"genesis/GsMainloop.hx",
"genesis/GsManagedData.hx",
"portal/Portal.hx",
#endif
 0 };

const char *__hxcpp_all_files_fullpath[] = {
#ifdef HXCPP_DEBUGGER
"/usr/share/haxe/std/cpp/_std/Std.hx",
"/usr/share/haxe/std/cpp/_std/haxe/Log.hx",
"/usr/share/haxe/std/haxe/io/Bytes.hx",
"/usr/share/haxe/std/haxe/iterators/ArrayIterator.hx",
"/home/mikaib/Documents/portal/Samples/1-Portal-and-Genesis/?",
"/home/mikaib/Documents/portal/Samples/1-Portal-and-Genesis/Source/Main.hx",
"/home/mikaib/Documents/genesis/Source/genesis/Genesis.hx",
"/home/mikaib/Documents/genesis/Source/genesis/GsMainloop.hx",
"/home/mikaib/Documents/genesis/Source/genesis/GsManagedData.hx",
"/home/mikaib/Documents/portal/Source/portal/Portal.hx",
#endif
 0 };

const char *__hxcpp_all_classes[] = {
#ifdef HXCPP_DEBUGGER
"Main",
"Std",
"genesis._Genesis",
"genesis.GsMainloop",
"genesis._GsManagedData.GsManagedDataHolder",
"genesis._GsManagedData.GsManagedData_Impl_",
"haxe.Log",
"haxe.io.Bytes",
"haxe.iterators.ArrayIterator",
"portal._Portal",
#endif
 0 };
} // namespace hx
void __files__boot() { __hxcpp_set_debugger_info(::hx::__hxcpp_all_classes, ::hx::__hxcpp_all_files_fullpath); }
