// Generated by Haxe 4.3.3
#include <hxcpp.h>

#ifndef INCLUDED_genesis__GsManagedData_GsManagedDataHolder
#include <genesis/_GsManagedData/GsManagedDataHolder.h>
#endif
#ifndef INCLUDED_genesis__GsManagedData_GsManagedData_Impl_
#include <genesis/_GsManagedData/GsManagedData_Impl_.h>
#endif

HX_LOCAL_STACK_FRAME(_hx_pos_519671e90382e9f0_29__new,"genesis._GsManagedData.GsManagedData_Impl_","_new",0x11900cbc,"genesis._GsManagedData.GsManagedData_Impl_._new","genesis/GsManagedData.hx",29,0x3bfa7668)
HX_LOCAL_STACK_FRAME(_hx_pos_519671e90382e9f0_34_fromIntArray,"genesis._GsManagedData.GsManagedData_Impl_","fromIntArray",0xb8b3b40f,"genesis._GsManagedData.GsManagedData_Impl_.fromIntArray","genesis/GsManagedData.hx",34,0x3bfa7668)
HX_LOCAL_STACK_FRAME(_hx_pos_519671e90382e9f0_40_fromFloatArray,"genesis._GsManagedData.GsManagedData_Impl_","fromFloatArray",0xe3506b82,"genesis._GsManagedData.GsManagedData_Impl_.fromFloatArray","genesis/GsManagedData.hx",40,0x3bfa7668)
namespace genesis{
namespace _GsManagedData{

void GsManagedData_Impl__obj::__construct() { }

Dynamic GsManagedData_Impl__obj::__CreateEmpty() { return new GsManagedData_Impl__obj; }

void *GsManagedData_Impl__obj::_hx_vtable = 0;

Dynamic GsManagedData_Impl__obj::__Create(::hx::DynamicArray inArgs)
{
	::hx::ObjectPtr< GsManagedData_Impl__obj > _hx_result = new GsManagedData_Impl__obj();
	_hx_result->__construct();
	return _hx_result;
}

bool GsManagedData_Impl__obj::_hx_isInstanceOf(int inClassId) {
	return inClassId==(int)0x00000001 || inClassId==(int)0x3374e337;
}

 ::genesis::_GsManagedData::GsManagedDataHolder GsManagedData_Impl__obj::_new(void * star,int size){
            	HX_GC_STACKFRAME(&_hx_pos_519671e90382e9f0_29__new)
HXLINE(  30)		 ::genesis::_GsManagedData::GsManagedDataHolder holder =  ::genesis::_GsManagedData::GsManagedDataHolder_obj::__alloc( HX_CTX );
HXDLIN(  30)		holder->ptr = star;
HXDLIN(  30)		holder->size = size;
HXLINE(  29)		return holder;
            	}


static ::Dynamic _hx_wrapGsManagedData_Impl__obj__new(  const Dynamic &a0,const Dynamic &a1) {
	return GsManagedData_Impl__obj::_new((cpp::Pointer<void >) a0,a1);
}
::Dynamic GsManagedData_Impl__obj::_new_dyn() {
	return ::hx::CreateStaticFunction2("_new",_hx_wrapGsManagedData_Impl__obj__new);}
 ::genesis::_GsManagedData::GsManagedDataHolder GsManagedData_Impl__obj::fromIntArray(::Array< int > data){
            	HX_STACKFRAME(&_hx_pos_519671e90382e9f0_34_fromIntArray)
HXLINE(  35)		::cpp::Pointer< void > ptr = ( (::cpp::Pointer< int >)(::cpp::Pointer_obj::arrayElem(data,0)) )->reinterpret();
HXLINE(  36)		return ::genesis::_GsManagedData::GsManagedData_Impl__obj::_new(ptr->ptr,(data->length * 4));
            	}


STATIC_HX_DEFINE_DYNAMIC_FUNC1(GsManagedData_Impl__obj,fromIntArray,return )

 ::genesis::_GsManagedData::GsManagedDataHolder GsManagedData_Impl__obj::fromFloatArray(::Array< float > data){
            	HX_STACKFRAME(&_hx_pos_519671e90382e9f0_40_fromFloatArray)
HXLINE(  41)		::cpp::Pointer< void > ptr = ( (::cpp::Pointer< float >)(::cpp::Pointer_obj::arrayElem(data,0)) )->reinterpret();
HXLINE(  42)		return ::genesis::_GsManagedData::GsManagedData_Impl__obj::_new(ptr->ptr,(data->length * 4));
            	}


STATIC_HX_DEFINE_DYNAMIC_FUNC1(GsManagedData_Impl__obj,fromFloatArray,return )


GsManagedData_Impl__obj::GsManagedData_Impl__obj()
{
}

bool GsManagedData_Impl__obj::__GetStatic(const ::String &inName, Dynamic &outValue, ::hx::PropertyAccess inCallProp)
{
	switch(inName.length) {
	case 4:
		if (HX_FIELD_EQ(inName,"_new") ) { outValue = _new_dyn(); return true; }
		break;
	case 12:
		if (HX_FIELD_EQ(inName,"fromIntArray") ) { outValue = fromIntArray_dyn(); return true; }
		break;
	case 14:
		if (HX_FIELD_EQ(inName,"fromFloatArray") ) { outValue = fromFloatArray_dyn(); return true; }
	}
	return false;
}

#ifdef HXCPP_SCRIPTABLE
static ::hx::StorageInfo *GsManagedData_Impl__obj_sMemberStorageInfo = 0;
static ::hx::StaticInfo *GsManagedData_Impl__obj_sStaticStorageInfo = 0;
#endif

::hx::Class GsManagedData_Impl__obj::__mClass;

static ::String GsManagedData_Impl__obj_sStaticFields[] = {
	HX_("_new",61,15,1f,3f),
	HX_("fromIntArray",b4,69,23,0e),
	HX_("fromFloatArray",67,94,54,3c),
	::String(null())
};

void GsManagedData_Impl__obj::__register()
{
	GsManagedData_Impl__obj _hx_dummy;
	GsManagedData_Impl__obj::_hx_vtable = *(void **)&_hx_dummy;
	::hx::Static(__mClass) = new ::hx::Class_obj();
	__mClass->mName = HX_("genesis._GsManagedData.GsManagedData_Impl_",f3,a6,1c,4b);
	__mClass->mSuper = &super::__SGetClass();
	__mClass->mConstructEmpty = &__CreateEmpty;
	__mClass->mConstructArgs = &__Create;
	__mClass->mGetStaticField = &GsManagedData_Impl__obj::__GetStatic;
	__mClass->mSetStaticField = &::hx::Class_obj::SetNoStaticField;
	__mClass->mStatics = ::hx::Class_obj::dupFunctions(GsManagedData_Impl__obj_sStaticFields);
	__mClass->mMembers = ::hx::Class_obj::dupFunctions(0 /* sMemberFields */);
	__mClass->mCanCast = ::hx::TCanCast< GsManagedData_Impl__obj >;
#ifdef HXCPP_SCRIPTABLE
	__mClass->mMemberStorageInfo = GsManagedData_Impl__obj_sMemberStorageInfo;
#endif
#ifdef HXCPP_SCRIPTABLE
	__mClass->mStaticStorageInfo = GsManagedData_Impl__obj_sStaticStorageInfo;
#endif
	::hx::_hx_RegisterClass(__mClass->mName, __mClass);
}

} // end namespace genesis
} // end namespace _GsManagedData
