// Generated by Haxe 4.3.6
#include <hxcpp.h>

#ifndef INCLUDED_4dbe585c96d08098
#define INCLUDED_4dbe585c96d08098
#include "genesis.h"
#endif
#ifndef INCLUDED_genesis_GsMainloop
#include <genesis/GsMainloop.h>
#endif
#ifndef INCLUDED_genesis__Genesis
#include <genesis/_Genesis.h>
#endif
#ifndef INCLUDED_genesis__GsManagedData_GsManagedDataHolder
#include <genesis/_GsManagedData/GsManagedDataHolder.h>
#endif
#ifndef INCLUDED_haxe_io_Bytes
#include <haxe/io/Bytes.h>
#endif

HX_LOCAL_STACK_FRAME(_hx_pos_22e0d60e36ba2919_264_layoutAdd,"genesis._Genesis","layoutAdd",0xcf4686f8,"genesis._Genesis.layoutAdd","genesis/Genesis.hx",264,0xf5d148fd)
HX_LOCAL_STACK_FRAME(_hx_pos_22e0d60e36ba2919_268_layoutBuild,"genesis._Genesis","layoutBuild",0xb1d793c5,"genesis._Genesis.layoutBuild","genesis/Genesis.hx",268,0xf5d148fd)
HX_LOCAL_STACK_FRAME(_hx_pos_22e0d60e36ba2919_272_init,"genesis._Genesis","init",0x89dcb14f,"genesis._Genesis.init","genesis/Genesis.hx",272,0xf5d148fd)
HX_LOCAL_STACK_FRAME(_hx_pos_22e0d60e36ba2919_276_shutdown,"genesis._Genesis","shutdown",0x625efe55,"genesis._Genesis.shutdown","genesis/Genesis.hx",276,0xf5d148fd)
HX_LOCAL_STACK_FRAME(_hx_pos_22e0d60e36ba2919_280_createConfig,"genesis._Genesis","createConfig",0xe717e41d,"genesis._Genesis.createConfig","genesis/Genesis.hx",280,0xf5d148fd)
HX_LOCAL_STACK_FRAME(_hx_pos_22e0d60e36ba2919_284_createBackend,"genesis._Genesis","createBackend",0x391dde59,"genesis._Genesis.createBackend","genesis/Genesis.hx",284,0xf5d148fd)
HX_LOCAL_STACK_FRAME(_hx_pos_22e0d60e36ba2919_288_createLayout,"genesis._Genesis","createLayout",0x77fe3c05,"genesis._Genesis.createLayout","genesis/Genesis.hx",288,0xf5d148fd)
HX_LOCAL_STACK_FRAME(_hx_pos_22e0d60e36ba2919_292_destroyConfig,"genesis._Genesis","destroyConfig",0xeb1f393d,"genesis._Genesis.destroyConfig","genesis/Genesis.hx",292,0xf5d148fd)
HX_LOCAL_STACK_FRAME(_hx_pos_22e0d60e36ba2919_296_destroyBackend,"genesis._Genesis","destroyBackend",0xbb810539,"genesis._Genesis.destroyBackend","genesis/Genesis.hx",296,0xf5d148fd)
HX_LOCAL_STACK_FRAME(_hx_pos_22e0d60e36ba2919_300_destroyLayout,"genesis._Genesis","destroyLayout",0x7c059125,"genesis._Genesis.destroyLayout","genesis/Genesis.hx",300,0xf5d148fd)
HX_LOCAL_STACK_FRAME(_hx_pos_22e0d60e36ba2919_304_getOptimalBackendType,"genesis._Genesis","getOptimalBackendType",0x6c4009a3,"genesis._Genesis.getOptimalBackendType","genesis/Genesis.hx",304,0xf5d148fd)
HX_LOCAL_STACK_FRAME(_hx_pos_22e0d60e36ba2919_308_createCommandList,"genesis._Genesis","createCommandList",0x0008e40e,"genesis._Genesis.createCommandList","genesis/Genesis.hx",308,0xf5d148fd)
HX_LOCAL_STACK_FRAME(_hx_pos_22e0d60e36ba2919_312_destroyCommandList,"genesis._Genesis","destroyCommandList",0x23b8faee,"genesis._Genesis.destroyCommandList","genesis/Genesis.hx",312,0xf5d148fd)
HX_LOCAL_STACK_FRAME(_hx_pos_22e0d60e36ba2919_316_commandListClear,"genesis._Genesis","commandListClear",0xf3f5f643,"genesis._Genesis.commandListClear","genesis/Genesis.hx",316,0xf5d148fd)
HX_LOCAL_STACK_FRAME(_hx_pos_22e0d60e36ba2919_320_commandListBegin,"genesis._Genesis","commandListBegin",0x5bf06edf,"genesis._Genesis.commandListBegin","genesis/Genesis.hx",320,0xf5d148fd)
HX_LOCAL_STACK_FRAME(_hx_pos_22e0d60e36ba2919_324_commandListEnd,"genesis._Genesis","commandListEnd",0x67b5cf11,"genesis._Genesis.commandListEnd","genesis/Genesis.hx",324,0xf5d148fd)
HX_LOCAL_STACK_FRAME(_hx_pos_22e0d60e36ba2919_328_commandListSubmit,"genesis._Genesis","commandListSubmit",0x159ff2a2,"genesis._Genesis.commandListSubmit","genesis/Genesis.hx",328,0xf5d148fd)
HX_LOCAL_STACK_FRAME(_hx_pos_22e0d60e36ba2919_332_clear,"genesis._Genesis","clear",0xa181726e,"genesis._Genesis.clear","genesis/Genesis.hx",332,0xf5d148fd)
HX_LOCAL_STACK_FRAME(_hx_pos_22e0d60e36ba2919_336_setViewport,"genesis._Genesis","setViewport",0x130975c9,"genesis._Genesis.setViewport","genesis/Genesis.hx",336,0xf5d148fd)
HX_LOCAL_STACK_FRAME(_hx_pos_22e0d60e36ba2919_340_usePipeline,"genesis._Genesis","usePipeline",0xeb92222a,"genesis._Genesis.usePipeline","genesis/Genesis.hx",340,0xf5d148fd)
HX_LOCAL_STACK_FRAME(_hx_pos_22e0d60e36ba2919_344_useBuffer,"genesis._Genesis","useBuffer",0xf86dd208,"genesis._Genesis.useBuffer","genesis/Genesis.hx",344,0xf5d148fd)
HX_LOCAL_STACK_FRAME(_hx_pos_22e0d60e36ba2919_348_useTexture,"genesis._Genesis","useTexture",0x54fa1ad3,"genesis._Genesis.useTexture","genesis/Genesis.hx",348,0xf5d148fd)
HX_LOCAL_STACK_FRAME(_hx_pos_22e0d60e36ba2919_352_frame,"genesis._Genesis","frame",0x5fa9790e,"genesis._Genesis.frame","genesis/Genesis.hx",352,0xf5d148fd)
HX_LOCAL_STACK_FRAME(_hx_pos_22e0d60e36ba2919_356_discardFrame,"genesis._Genesis","discardFrame",0x41cdae6e,"genesis._Genesis.discardFrame","genesis/Genesis.hx",356,0xf5d148fd)
HX_LOCAL_STACK_FRAME(_hx_pos_22e0d60e36ba2919_360_createPipeline,"genesis._Genesis","createPipeline",0xf14b953d,"genesis._Genesis.createPipeline","genesis/Genesis.hx",360,0xf5d148fd)
HX_LOCAL_STACK_FRAME(_hx_pos_22e0d60e36ba2919_364_destroyPipeline,"genesis._Genesis","destroyPipeline",0x85aa725d,"genesis._Genesis.destroyPipeline","genesis/Genesis.hx",364,0xf5d148fd)
HX_LOCAL_STACK_FRAME(_hx_pos_22e0d60e36ba2919_368_pipelineSetLayout,"genesis._Genesis","pipelineSetLayout",0xbe1822cb,"genesis._Genesis.pipelineSetLayout","genesis/Genesis.hx",368,0xf5d148fd)
HX_LOCAL_STACK_FRAME(_hx_pos_22e0d60e36ba2919_372_createBuffer,"genesis._Genesis","createBuffer",0xefda4a5b,"genesis._Genesis.createBuffer","genesis/Genesis.hx",372,0xf5d148fd)
HX_LOCAL_STACK_FRAME(_hx_pos_22e0d60e36ba2919_376_destroyBuffer,"genesis._Genesis","destroyBuffer",0xf3e19f7b,"genesis._Genesis.destroyBuffer","genesis/Genesis.hx",376,0xf5d148fd)
HX_LOCAL_STACK_FRAME(_hx_pos_22e0d60e36ba2919_380_bufferSetData,"genesis._Genesis","bufferSetData",0x92b8ebad,"genesis._Genesis.bufferSetData","genesis/Genesis.hx",380,0xf5d148fd)
HX_LOCAL_STACK_FRAME(_hx_pos_22e0d60e36ba2919_384_bufferSetPartialData,"genesis._Genesis","bufferSetPartialData",0x80d91f28,"genesis._Genesis.bufferSetPartialData","genesis/Genesis.hx",384,0xf5d148fd)
HX_LOCAL_STACK_FRAME(_hx_pos_22e0d60e36ba2919_388_destroyUnmanagedBufferData,"genesis._Genesis","destroyUnmanagedBufferData",0x64da74b5,"genesis._Genesis.destroyUnmanagedBufferData","genesis/Genesis.hx",388,0xf5d148fd)
HX_LOCAL_STACK_FRAME(_hx_pos_22e0d60e36ba2919_392_drawArrays,"genesis._Genesis","drawArrays",0xad1a235d,"genesis._Genesis.drawArrays","genesis/Genesis.hx",392,0xf5d148fd)
HX_LOCAL_STACK_FRAME(_hx_pos_22e0d60e36ba2919_396_drawIndexed,"genesis._Genesis","drawIndexed",0x700affee,"genesis._Genesis.drawIndexed","genesis/Genesis.hx",396,0xf5d148fd)
HX_LOCAL_STACK_FRAME(_hx_pos_22e0d60e36ba2919_400_setScissor,"genesis._Genesis","setScissor",0x0b2c7c19,"genesis._Genesis.setScissor","genesis/Genesis.hx",400,0xf5d148fd)
HX_LOCAL_STACK_FRAME(_hx_pos_22e0d60e36ba2919_404_disableScissor,"genesis._Genesis","disableScissor",0x55f3ce13,"genesis._Genesis.disableScissor","genesis/Genesis.hx",404,0xf5d148fd)
HX_LOCAL_STACK_FRAME(_hx_pos_22e0d60e36ba2919_408_createShader,"genesis._Genesis","createShader",0x3c664c80,"genesis._Genesis.createShader","genesis/Genesis.hx",408,0xf5d148fd)
HX_LOCAL_STACK_FRAME(_hx_pos_22e0d60e36ba2919_412_destroyShader,"genesis._Genesis","destroyShader",0x406da1a0,"genesis._Genesis.destroyShader","genesis/Genesis.hx",412,0xf5d148fd)
HX_LOCAL_STACK_FRAME(_hx_pos_22e0d60e36ba2919_416_createProgram,"genesis._Genesis","createProgram",0x318f6cc9,"genesis._Genesis.createProgram","genesis/Genesis.hx",416,0xf5d148fd)
HX_LOCAL_STACK_FRAME(_hx_pos_22e0d60e36ba2919_420_programAttachShader,"genesis._Genesis","programAttachShader",0x5c58860f,"genesis._Genesis.programAttachShader","genesis/Genesis.hx",420,0xf5d148fd)
HX_LOCAL_STACK_FRAME(_hx_pos_22e0d60e36ba2919_424_programBuild,"genesis._Genesis","programBuild",0x803eaf49,"genesis._Genesis.programBuild","genesis/Genesis.hx",424,0xf5d148fd)
HX_LOCAL_STACK_FRAME(_hx_pos_22e0d60e36ba2919_428_destroyProgram,"genesis._Genesis","destroyProgram",0xb3f293a9,"genesis._Genesis.destroyProgram","genesis/Genesis.hx",428,0xf5d148fd)
HX_LOCAL_STACK_FRAME(_hx_pos_22e0d60e36ba2919_432__createMainloop,"genesis._Genesis","_createMainloop",0x191dfaf9,"genesis._Genesis._createMainloop","genesis/Genesis.hx",432,0xf5d148fd)
HX_LOCAL_STACK_FRAME(_hx_pos_22e0d60e36ba2919_436_startMainloop,"genesis._Genesis","startMainloop",0x0f6f9b80,"genesis._Genesis.startMainloop","genesis/Genesis.hx",436,0xf5d148fd)
HX_LOCAL_STACK_FRAME(_hx_pos_22e0d60e36ba2919_440_stopMainloop,"genesis._Genesis","stopMainloop",0x23b1ba7e,"genesis._Genesis.stopMainloop","genesis/Genesis.hx",440,0xf5d148fd)
HX_LOCAL_STACK_FRAME(_hx_pos_22e0d60e36ba2919_444_createTexture,"genesis._Genesis","createTexture",0xdc76eb20,"genesis._Genesis.createTexture","genesis/Genesis.hx",444,0xf5d148fd)
HX_LOCAL_STACK_FRAME(_hx_pos_22e0d60e36ba2919_448_createTextureSimple,"genesis._Genesis","createTextureSimple",0xecbb7b72,"genesis._Genesis.createTextureSimple","genesis/Genesis.hx",448,0xf5d148fd)
HX_LOCAL_STACK_FRAME(_hx_pos_22e0d60e36ba2919_452_createCubemap,"genesis._Genesis","createCubemap",0xca7eb70c,"genesis._Genesis.createCubemap","genesis/Genesis.hx",452,0xf5d148fd)
HX_LOCAL_STACK_FRAME(_hx_pos_22e0d60e36ba2919_456_textureSetData,"genesis._Genesis","textureSetData",0x7d35f250,"genesis._Genesis.textureSetData","genesis/Genesis.hx",456,0xf5d148fd)
HX_LOCAL_STACK_FRAME(_hx_pos_22e0d60e36ba2919_460_textureSetFaceData,"genesis._Genesis","textureSetFaceData",0xe54ff08d,"genesis._Genesis.textureSetFaceData","genesis/Genesis.hx",460,0xf5d148fd)
HX_LOCAL_STACK_FRAME(_hx_pos_22e0d60e36ba2919_464_textureGenerateMipmaps,"genesis._Genesis","textureGenerateMipmaps",0xfafc529a,"genesis._Genesis.textureGenerateMipmaps","genesis/Genesis.hx",464,0xf5d148fd)
HX_LOCAL_STACK_FRAME(_hx_pos_22e0d60e36ba2919_468_destroyTexture,"genesis._Genesis","destroyTexture",0x5eda1200,"genesis._Genesis.destroyTexture","genesis/Genesis.hx",468,0xf5d148fd)
HX_LOCAL_STACK_FRAME(_hx_pos_22e0d60e36ba2919_472_getUniformLocation,"genesis._Genesis","getUniformLocation",0xd144a612,"genesis._Genesis.getUniformLocation","genesis/Genesis.hx",472,0xf5d148fd)
HX_LOCAL_STACK_FRAME(_hx_pos_22e0d60e36ba2919_476_uniformSetInt,"genesis._Genesis","uniformSetInt",0x373678a2,"genesis._Genesis.uniformSetInt","genesis/Genesis.hx",476,0xf5d148fd)
HX_LOCAL_STACK_FRAME(_hx_pos_22e0d60e36ba2919_480_uniformSetFloat,"genesis._Genesis","uniformSetFloat",0x90b5c40f,"genesis._Genesis.uniformSetFloat","genesis/Genesis.hx",480,0xf5d148fd)
HX_LOCAL_STACK_FRAME(_hx_pos_22e0d60e36ba2919_484_uniformSetVec2,"genesis._Genesis","uniformSetVec2",0x2103f84b,"genesis._Genesis.uniformSetVec2","genesis/Genesis.hx",484,0xf5d148fd)
HX_LOCAL_STACK_FRAME(_hx_pos_22e0d60e36ba2919_488_uniformSetVec3,"genesis._Genesis","uniformSetVec3",0x2103f84c,"genesis._Genesis.uniformSetVec3","genesis/Genesis.hx",488,0xf5d148fd)
HX_LOCAL_STACK_FRAME(_hx_pos_22e0d60e36ba2919_492_uniformSetVec4,"genesis._Genesis","uniformSetVec4",0x2103f84d,"genesis._Genesis.uniformSetVec4","genesis/Genesis.hx",492,0xf5d148fd)
HX_LOCAL_STACK_FRAME(_hx_pos_22e0d60e36ba2919_496_uniformSetMat4,"genesis._Genesis","uniformSetMat4",0x1b0e1281,"genesis._Genesis.uniformSetMat4","genesis/Genesis.hx",496,0xf5d148fd)
HX_LOCAL_STACK_FRAME(_hx_pos_22e0d60e36ba2919_500_copyTexture,"genesis._Genesis","copyTexture",0x3af8a547,"genesis._Genesis.copyTexture","genesis/Genesis.hx",500,0xf5d148fd)
HX_LOCAL_STACK_FRAME(_hx_pos_22e0d60e36ba2919_504_resolveTexture,"genesis._Genesis","resolveTexture",0x4ae6ae4e,"genesis._Genesis.resolveTexture","genesis/Genesis.hx",504,0xf5d148fd)
HX_LOCAL_STACK_FRAME(_hx_pos_22e0d60e36ba2919_508_copyTexturePartial,"genesis._Genesis","copyTexturePartial",0xac91a0fa,"genesis._Genesis.copyTexturePartial","genesis/Genesis.hx",508,0xf5d148fd)
HX_LOCAL_STACK_FRAME(_hx_pos_22e0d60e36ba2919_512_generateMipmaps,"genesis._Genesis","generateMipmaps",0x19303757,"genesis._Genesis.generateMipmaps","genesis/Genesis.hx",512,0xf5d148fd)
HX_LOCAL_STACK_FRAME(_hx_pos_22e0d60e36ba2919_516_createRenderPass,"genesis._Genesis","createRenderPass",0x7262b622,"genesis._Genesis.createRenderPass","genesis/Genesis.hx",516,0xf5d148fd)
HX_LOCAL_STACK_FRAME(_hx_pos_22e0d60e36ba2919_520_destroyRenderPass,"genesis._Genesis","destroyRenderPass",0x020b1b42,"genesis._Genesis.destroyRenderPass","genesis/Genesis.hx",520,0xf5d148fd)
HX_LOCAL_STACK_FRAME(_hx_pos_22e0d60e36ba2919_524_beginRenderPass,"genesis._Genesis","beginRenderPass",0xe46cbef1,"genesis._Genesis.beginRenderPass","genesis/Genesis.hx",524,0xf5d148fd)
HX_LOCAL_STACK_FRAME(_hx_pos_22e0d60e36ba2919_528_endRenderPass,"genesis._Genesis","endRenderPass",0x4f74b0e3,"genesis._Genesis.endRenderPass","genesis/Genesis.hx",528,0xf5d148fd)
HX_LOCAL_STACK_FRAME(_hx_pos_22e0d60e36ba2919_532_hasCapability,"genesis._Genesis","hasCapability",0x6d6275b3,"genesis._Genesis.hasCapability","genesis/Genesis.hx",532,0xf5d148fd)
HX_LOCAL_STACK_FRAME(_hx_pos_22e0d60e36ba2919_536_textureClear,"genesis._Genesis","textureClear",0x3deb6bf1,"genesis._Genesis.textureClear","genesis/Genesis.hx",536,0xf5d148fd)
HX_LOCAL_STACK_FRAME(_hx_pos_22e0d60e36ba2919_540_createFramebuffer,"genesis._Genesis","createFramebuffer",0x953d3db2,"genesis._Genesis.createFramebuffer","genesis/Genesis.hx",540,0xf5d148fd)
HX_LOCAL_STACK_FRAME(_hx_pos_22e0d60e36ba2919_544_destroyFramebuffer,"genesis._Genesis","destroyFramebuffer",0xb8ed5492,"genesis._Genesis.destroyFramebuffer","genesis/Genesis.hx",544,0xf5d148fd)
HX_LOCAL_STACK_FRAME(_hx_pos_22e0d60e36ba2919_548_framebufferAttachTexture,"genesis._Genesis","framebufferAttachTexture",0x3069c228,"genesis._Genesis.framebufferAttachTexture","genesis/Genesis.hx",548,0xf5d148fd)
namespace genesis{

void _Genesis_obj::__construct() { }

Dynamic _Genesis_obj::__CreateEmpty() { return new _Genesis_obj; }

void *_Genesis_obj::_hx_vtable = 0;

Dynamic _Genesis_obj::__Create(::hx::DynamicArray inArgs)
{
	::hx::ObjectPtr< _Genesis_obj > _hx_result = new _Genesis_obj();
	_hx_result->__construct();
	return _hx_result;
}

bool _Genesis_obj::_hx_isInstanceOf(int inClassId) {
	return inClassId==(int)0x00000001 || inClassId==(int)0x7ff86a2d;
}

bool _Genesis_obj::layoutAdd( GsVtxLayout * layout,int index, cpp::Struct<GsVtxAttribType> type,int count){
            	HX_STACKFRAME(&_hx_pos_22e0d60e36ba2919_264_layoutAdd)
HXDLIN( 264)		return gs_layout_add(layout,index,type,count);
            	}


void _Genesis_obj::layoutBuild( GsVtxLayout * layout){
            	HX_STACKFRAME(&_hx_pos_22e0d60e36ba2919_268_layoutBuild)
HXDLIN( 268)		gs_layout_build(layout);
            	}


bool _Genesis_obj::init( GsConfig * config){
            	HX_STACKFRAME(&_hx_pos_22e0d60e36ba2919_272_init)
HXDLIN( 272)		return gs_init(config);
            	}


void _Genesis_obj::shutdown(){
            	HX_STACKFRAME(&_hx_pos_22e0d60e36ba2919_276_shutdown)
HXDLIN( 276)		gs_shutdown();
            	}


 GsConfig * _Genesis_obj::createConfig(){
            	HX_STACKFRAME(&_hx_pos_22e0d60e36ba2919_280_createConfig)
HXDLIN( 280)		return gs_create_config();
            	}


 GsBackend * _Genesis_obj::createBackend( cpp::Struct<GsBackendType> type){
            	HX_STACKFRAME(&_hx_pos_22e0d60e36ba2919_284_createBackend)
HXDLIN( 284)		return gs_create_backend(type);
            	}


 GsVtxLayout * _Genesis_obj::createLayout(){
            	HX_STACKFRAME(&_hx_pos_22e0d60e36ba2919_288_createLayout)
HXDLIN( 288)		return gs_create_layout();
            	}


void _Genesis_obj::destroyConfig( GsConfig * config){
            	HX_STACKFRAME(&_hx_pos_22e0d60e36ba2919_292_destroyConfig)
HXDLIN( 292)		gs_destroy_config(config);
            	}


void _Genesis_obj::destroyBackend( GsBackend * backend){
            	HX_STACKFRAME(&_hx_pos_22e0d60e36ba2919_296_destroyBackend)
HXDLIN( 296)		gs_destroy_backend(backend);
            	}


void _Genesis_obj::destroyLayout( GsVtxLayout * layout){
            	HX_STACKFRAME(&_hx_pos_22e0d60e36ba2919_300_destroyLayout)
HXDLIN( 300)		gs_destroy_layout(layout);
            	}


 cpp::Struct<GsBackendType> _Genesis_obj::getOptimalBackendType(){
            	HX_STACKFRAME(&_hx_pos_22e0d60e36ba2919_304_getOptimalBackendType)
HXDLIN( 304)		return gs_get_optimal_backend_type();
            	}


 GsCommandList * _Genesis_obj::createCommandList(){
            	HX_STACKFRAME(&_hx_pos_22e0d60e36ba2919_308_createCommandList)
HXDLIN( 308)		return gs_create_command_list();
            	}


void _Genesis_obj::destroyCommandList( GsCommandList * list){
            	HX_STACKFRAME(&_hx_pos_22e0d60e36ba2919_312_destroyCommandList)
HXDLIN( 312)		gs_destroy_command_list(list);
            	}


void _Genesis_obj::commandListClear( GsCommandList * list){
            	HX_STACKFRAME(&_hx_pos_22e0d60e36ba2919_316_commandListClear)
HXDLIN( 316)		gs_command_list_clear(list);
            	}


void _Genesis_obj::commandListBegin( GsCommandList * list){
            	HX_STACKFRAME(&_hx_pos_22e0d60e36ba2919_320_commandListBegin)
HXDLIN( 320)		gs_command_list_begin(list);
            	}


void _Genesis_obj::commandListEnd( GsCommandList * list){
            	HX_STACKFRAME(&_hx_pos_22e0d60e36ba2919_324_commandListEnd)
HXDLIN( 324)		gs_command_list_end(list);
            	}


void _Genesis_obj::commandListSubmit( GsCommandList * list){
            	HX_STACKFRAME(&_hx_pos_22e0d60e36ba2919_328_commandListSubmit)
HXDLIN( 328)		gs_command_list_submit(list);
            	}


void _Genesis_obj::clear( GsCommandList * list,int flags,Float r,Float g,Float b,Float a){
            	HX_STACKFRAME(&_hx_pos_22e0d60e36ba2919_332_clear)
HXDLIN( 332)		gs_clear(list,(GsClearFlags)flags,r,g,b,a);
            	}


void _Genesis_obj::setViewport( GsCommandList * list,int x,int y,int width,int height){
            	HX_STACKFRAME(&_hx_pos_22e0d60e36ba2919_336_setViewport)
HXDLIN( 336)		gs_set_viewport(list,x,y,width,height);
            	}


void _Genesis_obj::usePipeline( GsCommandList * list, GsPipeline * pipeline){
            	HX_STACKFRAME(&_hx_pos_22e0d60e36ba2919_340_usePipeline)
HXDLIN( 340)		gs_use_pipeline(list,pipeline);
            	}


void _Genesis_obj::useBuffer( GsCommandList * list, GsBuffer * buffer){
            	HX_STACKFRAME(&_hx_pos_22e0d60e36ba2919_344_useBuffer)
HXDLIN( 344)		gs_use_buffer(list,buffer);
            	}


void _Genesis_obj::useTexture( GsCommandList * list, GsTexture * texture,int slot){
            	HX_STACKFRAME(&_hx_pos_22e0d60e36ba2919_348_useTexture)
HXDLIN( 348)		gs_use_texture(list,texture,slot);
            	}


void _Genesis_obj::frame(){
            	HX_STACKFRAME(&_hx_pos_22e0d60e36ba2919_352_frame)
HXDLIN( 352)		gs_frame();
            	}


void _Genesis_obj::discardFrame(){
            	HX_STACKFRAME(&_hx_pos_22e0d60e36ba2919_356_discardFrame)
HXDLIN( 356)		gs_discard_frame();
            	}


 GsPipeline * _Genesis_obj::createPipeline(){
            	HX_STACKFRAME(&_hx_pos_22e0d60e36ba2919_360_createPipeline)
HXDLIN( 360)		return gs_create_pipeline();
            	}


void _Genesis_obj::destroyPipeline( GsPipeline * pipeline){
            	HX_STACKFRAME(&_hx_pos_22e0d60e36ba2919_364_destroyPipeline)
HXDLIN( 364)		gs_destroy_pipeline(pipeline);
            	}


void _Genesis_obj::pipelineSetLayout( GsPipeline * pipeline, GsVtxLayout * layout){
            	HX_STACKFRAME(&_hx_pos_22e0d60e36ba2919_368_pipelineSetLayout)
HXDLIN( 368)		gs_pipeline_set_layout(pipeline,layout);
            	}


 GsBuffer * _Genesis_obj::createBuffer( cpp::Struct<GsBufferType> type, cpp::Struct<GsBufferIntent> intent){
            	HX_STACKFRAME(&_hx_pos_22e0d60e36ba2919_372_createBuffer)
HXDLIN( 372)		return gs_create_buffer(type,intent);
            	}


void _Genesis_obj::destroyBuffer( GsBuffer * buffer){
            	HX_STACKFRAME(&_hx_pos_22e0d60e36ba2919_376_destroyBuffer)
HXDLIN( 376)		gs_destroy_buffer(buffer);
            	}


void _Genesis_obj::bufferSetData( GsBuffer * buffer, ::genesis::_GsManagedData::GsManagedDataHolder data){
            	HX_STACKFRAME(&_hx_pos_22e0d60e36ba2919_380_bufferSetData)
HXDLIN( 380)		gs_buffer_set_data(buffer,data->ptr,data->size);
            	}


void _Genesis_obj::bufferSetPartialData( GsBuffer * buffer, ::genesis::_GsManagedData::GsManagedDataHolder data,int offset){
            	HX_STACKFRAME(&_hx_pos_22e0d60e36ba2919_384_bufferSetPartialData)
HXDLIN( 384)		gs_buffer_set_partial_data(buffer,data->ptr,data->size,offset);
            	}


void _Genesis_obj::destroyUnmanagedBufferData( GsUnmanagedBufferData * data){
            	HX_STACKFRAME(&_hx_pos_22e0d60e36ba2919_388_destroyUnmanagedBufferData)
HXDLIN( 388)		gs_destroy_unmanaged_buffer_data(data);
            	}


void _Genesis_obj::drawArrays( GsCommandList * list,int start,int count){
            	HX_STACKFRAME(&_hx_pos_22e0d60e36ba2919_392_drawArrays)
HXDLIN( 392)		gs_draw_arrays(list,start,count);
            	}


void _Genesis_obj::drawIndexed( GsCommandList * list,int count){
            	HX_STACKFRAME(&_hx_pos_22e0d60e36ba2919_396_drawIndexed)
HXDLIN( 396)		gs_draw_indexed(list,count);
            	}


void _Genesis_obj::setScissor( GsCommandList * list,int x,int y,int width,int height){
            	HX_STACKFRAME(&_hx_pos_22e0d60e36ba2919_400_setScissor)
HXDLIN( 400)		gs_set_scissor(list,x,y,width,height);
            	}


void _Genesis_obj::disableScissor( GsCommandList * list){
            	HX_STACKFRAME(&_hx_pos_22e0d60e36ba2919_404_disableScissor)
HXDLIN( 404)		gs_disable_scissor(list);
            	}


 GsShader * _Genesis_obj::createShader( cpp::Struct<GsShaderType> type,const char* source){
            	HX_STACKFRAME(&_hx_pos_22e0d60e36ba2919_408_createShader)
HXDLIN( 408)		return gs_create_shader(type,source);
            	}


void _Genesis_obj::destroyShader( GsShader * shader){
            	HX_STACKFRAME(&_hx_pos_22e0d60e36ba2919_412_destroyShader)
HXDLIN( 412)		gs_destroy_shader(shader);
            	}


 GsProgram * _Genesis_obj::createProgram(){
            	HX_STACKFRAME(&_hx_pos_22e0d60e36ba2919_416_createProgram)
HXDLIN( 416)		return gs_create_program();
            	}


void _Genesis_obj::programAttachShader( GsProgram * program, GsShader * shader){
            	HX_STACKFRAME(&_hx_pos_22e0d60e36ba2919_420_programAttachShader)
HXDLIN( 420)		gs_program_attach_shader(program,shader);
            	}


void _Genesis_obj::programBuild( GsProgram * program){
            	HX_STACKFRAME(&_hx_pos_22e0d60e36ba2919_424_programBuild)
HXDLIN( 424)		gs_program_build(program);
            	}


void _Genesis_obj::destroyProgram( GsProgram * program){
            	HX_STACKFRAME(&_hx_pos_22e0d60e36ba2919_428_destroyProgram)
HXDLIN( 428)		gs_destroy_program(program);
            	}


void _Genesis_obj::_createMainloop(::cpp::Function< void  () > fn){
            	HX_STACKFRAME(&_hx_pos_22e0d60e36ba2919_432__createMainloop)
HXDLIN( 432)		gs_create_mainloop(fn);
            	}


void _Genesis_obj::startMainloop( ::Dynamic fn){
            	HX_STACKFRAME(&_hx_pos_22e0d60e36ba2919_436_startMainloop)
HXDLIN( 436)		::genesis::GsMainloop_obj::start(fn);
            	}


void _Genesis_obj::stopMainloop(){
            	HX_STACKFRAME(&_hx_pos_22e0d60e36ba2919_440_stopMainloop)
HXDLIN( 440)		gs_stop_mainloop();
            	}


 GsTexture * _Genesis_obj::createTexture(int width,int height, cpp::Struct<GsTextureFormat> format, cpp::Struct<GsTextureWrap> wrapS, cpp::Struct<GsTextureWrap> wrapT, cpp::Struct<GsTextureFilter> min, cpp::Struct<GsTextureFilter> mag){
            	HX_STACKFRAME(&_hx_pos_22e0d60e36ba2919_444_createTexture)
HXDLIN( 444)		return gs_create_texture(width,height,format,wrapS,wrapT,min,mag);
            	}


 GsTexture * _Genesis_obj::createTextureSimple(int width,int height, cpp::Struct<GsTextureFormat> format){
            	HX_STACKFRAME(&_hx_pos_22e0d60e36ba2919_448_createTextureSimple)
HXDLIN( 448)		return gs_create_texture(width,height,format,GS_TEXTURE_WRAP_CLAMP,GS_TEXTURE_WRAP_CLAMP,GS_TEXTURE_FILTER_LINEAR,GS_TEXTURE_FILTER_LINEAR);
            	}


 GsTexture * _Genesis_obj::createCubemap(int width,int height, cpp::Struct<GsTextureFormat> format, cpp::Struct<GsTextureWrap> wrapS, cpp::Struct<GsTextureWrap> wrapT, cpp::Struct<GsTextureWrap> wrapR, cpp::Struct<GsTextureFilter> min, cpp::Struct<GsTextureFilter> mag){
            	HX_STACKFRAME(&_hx_pos_22e0d60e36ba2919_452_createCubemap)
HXDLIN( 452)		return gs_create_cubemap(width,height,format,wrapS,wrapT,wrapR,min,mag);
            	}


void _Genesis_obj::textureSetData( GsTexture * texture, ::haxe::io::Bytes data){
            	HX_STACKFRAME(&_hx_pos_22e0d60e36ba2919_456_textureSetData)
HXDLIN( 456)		::cpp::Pointer< unsigned char > ptr = ( (::cpp::Pointer< unsigned char >)(::cpp::Pointer_obj::arrayElem(data->b,0)) );
HXDLIN( 456)		::cpp::Pointer< void > ptr1 = ptr->reinterpret();
HXDLIN( 456)		gs_texture_set_data(texture,ptr1->ptr);
            	}


void _Genesis_obj::textureSetFaceData( GsTexture * texture, cpp::Struct<GsCubemapFace> face, ::haxe::io::Bytes data){
            	HX_STACKFRAME(&_hx_pos_22e0d60e36ba2919_460_textureSetFaceData)
HXDLIN( 460)		::cpp::Pointer< unsigned char > ptr = ( (::cpp::Pointer< unsigned char >)(::cpp::Pointer_obj::arrayElem(data->b,0)) );
HXDLIN( 460)		::cpp::Pointer< void > ptr1 = ptr->reinterpret();
HXDLIN( 460)		gs_texture_set_face_data(texture,face,ptr1->ptr);
            	}


void _Genesis_obj::textureGenerateMipmaps( GsTexture * texture){
            	HX_STACKFRAME(&_hx_pos_22e0d60e36ba2919_464_textureGenerateMipmaps)
HXDLIN( 464)		gs_texture_generate_mipmaps(texture);
            	}


void _Genesis_obj::destroyTexture( GsTexture * texture){
            	HX_STACKFRAME(&_hx_pos_22e0d60e36ba2919_468_destroyTexture)
HXDLIN( 468)		gs_destroy_texture(texture);
            	}


int _Genesis_obj::getUniformLocation( GsProgram * program,const char* name){
            	HX_STACKFRAME(&_hx_pos_22e0d60e36ba2919_472_getUniformLocation)
HXDLIN( 472)		return gs_get_uniform_location(program,name);
            	}


void _Genesis_obj::uniformSetInt( GsCommandList * list,int location,int value){
            	HX_STACKFRAME(&_hx_pos_22e0d60e36ba2919_476_uniformSetInt)
HXDLIN( 476)		gs_uniform_set_int(list,location,value);
            	}


void _Genesis_obj::uniformSetFloat( GsCommandList * list,int location,float value){
            	HX_STACKFRAME(&_hx_pos_22e0d60e36ba2919_480_uniformSetFloat)
HXDLIN( 480)		gs_uniform_set_float(list,location,value);
            	}


void _Genesis_obj::uniformSetVec2( GsCommandList * list,int location,float x,float y){
            	HX_STACKFRAME(&_hx_pos_22e0d60e36ba2919_484_uniformSetVec2)
HXDLIN( 484)		gs_uniform_set_vec2(list,location,x,y);
            	}


void _Genesis_obj::uniformSetVec3( GsCommandList * list,int location,float x,float y,float z){
            	HX_STACKFRAME(&_hx_pos_22e0d60e36ba2919_488_uniformSetVec3)
HXDLIN( 488)		gs_uniform_set_vec3(list,location,x,y,z);
            	}


void _Genesis_obj::uniformSetVec4( GsCommandList * list,int location,float x,float y,float z,float w){
            	HX_STACKFRAME(&_hx_pos_22e0d60e36ba2919_492_uniformSetVec4)
HXDLIN( 492)		gs_uniform_set_vec4(list,location,x,y,z,w);
            	}


void _Genesis_obj::uniformSetMat4( GsCommandList * list,int location,float m00,float m01,float m02,float m03,float m10,float m11,float m12,float m13,float m20,float m21,float m22,float m23,float m30,float m31,float m32,float m33){
            	HX_STACKFRAME(&_hx_pos_22e0d60e36ba2919_496_uniformSetMat4)
HXDLIN( 496)		gs_uniform_set_mat4(list,location,m00,m01,m02,m03,m10,m11,m12,m13,m20,m21,m22,m23,m30,m31,m32,m33);
            	}


void _Genesis_obj::copyTexture( GsCommandList * list, GsTexture * src, GsTexture * dst){
            	HX_STACKFRAME(&_hx_pos_22e0d60e36ba2919_500_copyTexture)
HXDLIN( 500)		gs_copy_texture(list,src,dst);
            	}


void _Genesis_obj::resolveTexture( GsCommandList * list, GsTexture * src, GsTexture * dst){
            	HX_STACKFRAME(&_hx_pos_22e0d60e36ba2919_504_resolveTexture)
HXDLIN( 504)		gs_resolve_texture(list,src,dst);
            	}


void _Genesis_obj::copyTexturePartial( GsCommandList * list, GsTexture * src, GsTexture * dst,int srcX,int srcY,int dstX,int dstY,int width,int height){
            	HX_STACKFRAME(&_hx_pos_22e0d60e36ba2919_508_copyTexturePartial)
HXDLIN( 508)		gs_copy_texture_partial(list,src,dst,srcX,srcY,dstX,dstY,width,height);
            	}


void _Genesis_obj::generateMipmaps( GsCommandList * list, GsTexture * texture){
            	HX_STACKFRAME(&_hx_pos_22e0d60e36ba2919_512_generateMipmaps)
HXDLIN( 512)		gs_generate_mipmaps(list,texture);
            	}


 GsRenderPass * _Genesis_obj::createRenderPass( GsFramebuffer * fb){
            	HX_STACKFRAME(&_hx_pos_22e0d60e36ba2919_516_createRenderPass)
HXDLIN( 516)		return gs_create_render_pass(fb);
            	}


void _Genesis_obj::destroyRenderPass( GsRenderPass * pass){
            	HX_STACKFRAME(&_hx_pos_22e0d60e36ba2919_520_destroyRenderPass)
HXDLIN( 520)		gs_destroy_render_pass(pass);
            	}


void _Genesis_obj::beginRenderPass( GsCommandList * list, GsRenderPass * pass){
            	HX_STACKFRAME(&_hx_pos_22e0d60e36ba2919_524_beginRenderPass)
HXDLIN( 524)		gs_begin_render_pass(list,pass);
            	}


void _Genesis_obj::endRenderPass( GsCommandList * list){
            	HX_STACKFRAME(&_hx_pos_22e0d60e36ba2919_528_endRenderPass)
HXDLIN( 528)		gs_end_render_pass(list);
            	}


int _Genesis_obj::hasCapability( cpp::Struct<GsCapability> cap){
            	HX_STACKFRAME(&_hx_pos_22e0d60e36ba2919_532_hasCapability)
HXDLIN( 532)		return gs_has_capability(cap);
            	}


void _Genesis_obj::textureClear( GsTexture * texture){
            	HX_STACKFRAME(&_hx_pos_22e0d60e36ba2919_536_textureClear)
HXDLIN( 536)		gs_texture_clear(texture);
            	}


 GsFramebuffer * _Genesis_obj::createFramebuffer(int width,int height){
            	HX_STACKFRAME(&_hx_pos_22e0d60e36ba2919_540_createFramebuffer)
HXDLIN( 540)		return gs_create_framebuffer(width,height);
            	}


void _Genesis_obj::destroyFramebuffer( GsFramebuffer * fb){
            	HX_STACKFRAME(&_hx_pos_22e0d60e36ba2919_544_destroyFramebuffer)
HXDLIN( 544)		gs_destroy_framebuffer(fb);
            	}


void _Genesis_obj::framebufferAttachTexture( GsFramebuffer * fb, GsTexture * texture, cpp::Struct<GsFramebufferAttachmentType> attachment){
            	HX_STACKFRAME(&_hx_pos_22e0d60e36ba2919_548_framebufferAttachTexture)
HXDLIN( 548)		gs_framebuffer_attach_texture(fb,texture,attachment);
            	}



_Genesis_obj::_Genesis_obj()
{
}

#ifdef HXCPP_SCRIPTABLE
static ::hx::StorageInfo *_Genesis_obj_sMemberStorageInfo = 0;
static ::hx::StaticInfo *_Genesis_obj_sStaticStorageInfo = 0;
#endif

::hx::Class _Genesis_obj::__mClass;

void _Genesis_obj::__register()
{
	_Genesis_obj _hx_dummy;
	_Genesis_obj::_hx_vtable = *(void **)&_hx_dummy;
	::hx::Static(__mClass) = new ::hx::Class_obj();
	__mClass->mName = HX_("genesis._Genesis",8f,92,84,81);
	__mClass->mSuper = &super::__SGetClass();
	__mClass->mConstructEmpty = &__CreateEmpty;
	__mClass->mConstructArgs = &__Create;
	__mClass->mGetStaticField = &::hx::Class_obj::GetNoStaticField;
	__mClass->mSetStaticField = &::hx::Class_obj::SetNoStaticField;
	__mClass->mStatics = ::hx::Class_obj::dupFunctions(0 /* sStaticFields */);
	__mClass->mMembers = ::hx::Class_obj::dupFunctions(0 /* sMemberFields */);
	__mClass->mCanCast = ::hx::TCanCast< _Genesis_obj >;
#ifdef HXCPP_SCRIPTABLE
	__mClass->mMemberStorageInfo = _Genesis_obj_sMemberStorageInfo;
#endif
#ifdef HXCPP_SCRIPTABLE
	__mClass->mStaticStorageInfo = _Genesis_obj_sStaticStorageInfo;
#endif
	::hx::_hx_RegisterClass(__mClass->mName, __mClass);
}

} // end namespace genesis
